### ISSUE TITLE
Publicar en Google Play

### ISSUE THREAD

**Issue by ifh1001** [dgm1003/GESPRO_PracticaGestionTareas_2021#24]
https://support.google.com/googleplay/android-developer/answer/113469#privacy

https://www.raywenderlich.com/122114/android-app-distribution-tutorial-zero-google-play-store

**Comment by dgm1003** [comment]
![imagen](https://user-images.githubusercontent.com/74530621/99909686-4a923f80-2cea-11eb-8d1a-5856f0b230f7.png)
![imagen](https://user-images.githubusercontent.com/74530621/99909694-54b43e00-2cea-11eb-8b79-898b766845b6.png)
![imagen](https://user-images.githubusercontent.com/74530621/99909698-5c73e280-2cea-11eb-8232-343f3b308ed4.png)
![imagen](https://user-images.githubusercontent.com/74530621/99909702-6269c380-2cea-11eb-812e-f6841a7548c6.png)
![imagen](https://user-images.githubusercontent.com/74530621/99909705-6990d180-2cea-11eb-97ca-dbe33f3b9f9f.png)
![imagen](https://user-images.githubusercontent.com/74530621/99909710-6f86b280-2cea-11eb-90fd-e508c8d98f39.png)

**Comment by ifh1001** [comment]
https://play.google.com/store/apps/details?id=com.davidmiguel.gobees
